# Restart `bundle exec jekyll serve --livereload` after editing this file.
title: Jacob Poschl
email: jake.poschl@gmail.com
description: >-
  Jacob Poschl Research Portfolio.
url: "https://jacobposchl.github.io"
baseurl: ""
github_username: jacobposchl

markdown: kramdown
theme: null
sass:
  sass_dir: assets/styles
  style: compressed

include:
  - _pages
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - .bundle

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name: "Jacob Poschl"
  avatar: "/assets/images/profile/graduation.jpeg"
  bio: "NerDS Lab @ UPenn<br>B.S. Computer Science @ UCSC"
  links:
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/jacobposchl/"
    - label: "Email"
      url: "mailto:jake.poschl@gmail.com"
    - label: "GitHub"
      url: "https://github.com/jacobposchl"

defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: article
